### PR TITLE
Added XPath and Sorting for dynamic series (see issue #54)

### PR DESCRIPTION
**Pull request by rik-bos**
Hi all,

I created the possibility to add a sorting attribute (name is used when empty) as well as XPath for the dynamic series (as requested in #54).

It is tested and backwards compatible.

Kind regards,
Rik Bos

### CODE REVIEW

**Comment by djkwagala** [comment]
Hello @rik-bos thanks for your contribution.
I shared a possible beta release earlier this morning in response to issue #56 
Have you checked it out?
I'll add here.
https://github.com/mendixlabs/charts/issues/56#issuecomment-419818991

**Comment by rik-bos** [comment]
Hi Derrick,

I checked that version. It doesn't solve the issue for me that I cannot use an xpath constraint for my Series entity. I'll have more than one chart instance using the same domain model for the same user, so I cannot circomvent this by using entity access. That's why I did the change.

So that's why I came up with this pull request (which does do the trick for me) and I assume also for @Narev.

Kind regards,
Rik Bos

**Comment by djkwagala** [comment]
Hello Rik,
I'm trying to understand how it's not possible to constrain series entity
with XPath starting from values entity over association of the
seriesEntity.
Actually we have tested that use case on multiple instances in the test
project.
Check it out and see how we did it.

[domain]/p/dynamicseries.

**Comment by rik-bos** [comment]
Hi Derrick,

From a visual perspective it is indeed limiting over the valuesEntity. However, it will retrieve all the objects from the seriesEntity that are allowed by the the security roles, from that it will retrieve all the values associated to them (and hide the series without values). Which means that the load on the server is way too high if there are multiple graphs using different / historical objects.

Kind regards,
Rik Bos

**Comment by diego-antonelli** [comment]
Closed due to lots of conflicts

**Pull request closed without merging**
