### PR TITLE
[WC-1115] fix: issue with preview rendering for charts v1

### PR DESCRIPTION
**Pull request by raffiar**

### CODE REVIEW

**Review by iobuhov — DISMISSED** [review]
Can we have special logger.ts module where we will export `logger` const and depending on current env?
```
declare global {
    interface Window {
        mx: { logger: Function };
        logger: Function;
    }
}

function resolveLogger() {
    if (window.mx && window.mx.logger) {
        return window.mx.logger;
    } else if (window.logger) {
        return window.logger;
    } else {
        throw new Error("Unable to find logger in global scope.");
    }
}

export const logger = resolveLogger();
```

**Review by iobuhov — CHANGES_REQUESTED** [review]
Please read my comment, I think same applies to second PR

**Comment by raffiar** [comment]
> Can we have special logger.ts module where we will export `logger` const and depending on current env?
> 
> ```
> declare global {
>     interface Window {
>         mx: { logger: Function };
>         logger: Function;
>     }
> }
> 
> function resolveLogger() {
>     if (window.mx && window.mx.logger) {
>         return window.mx.logger;
>     } else if (window.logger) {
>         return window.logger;
>     } else {
>         throw new Error("Unable to find logger in global scope.");
>     }
> }
> 
> export const logger = resolveLogger();
> ```

This doesn't make sense. I spoke with Takuma, and he said that `mx` object never can be accessed from design mode.
So what Diego did here should be reverted, cuz it will never work.

**Comment by iobuhov** [comment]
Okay, I see. But also, I see that Diego was trying to fix warnings. Can you chage if this line causes warnings and if so add eslint ignore statement?

**Review by iobuhov — APPROVED** [review]

**Comment by raffiar** [comment]
> Okay, I see. But also, I see that Diego was trying to fix warnings. Can you chage if this line causes warnings and if so add eslint ignore statement?

No warnings left! 👯

**Review by leonardomendix — APPROVED** [review]

**Pull request merged**
